[[bin]]
name = "generics"
path = "src/main.rs"

[lib]
name = "aggregator"
path = "aggregator/src/lib.rs"

[package]
name = "generics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



